export const FEATURE_FLAGS = {
  HEADLINER_ANNOUNCEMENT: 'HEADLINER_ANNOUNCEMENT',
  SHOW_EMAIL_CAPTURE: 'SHOW_EMAIL_CAPTURE',
  TICKET_SALES_OPEN: 'TICKET_SALES_OPEN',
  ENABLE_PROMO_CODE: 'ENABLE_PROMO_CODE',
  ENABLE_CABIN_RESERVATION_EMAIL: 'ENABLE_CABIN_RESERVATION_EMAIL',
  ENABLE_CHECK_IN: 'ENABLE_CHECK_IN',
  VENDOR_TICKETS_OPEN: 'VENDOR_TICKETS_OPEN',
  ENABLE_ARTIST_SUBMISSIONS: 'ENABLE_ARTIST_SUBMISSIONS',
  IS_FESTIVAL_TRANSITION_PERIOD: 'IS_FESTIVAL_TRANSITION_PERIOD',
} as const;

export const MAP_URLS_TO_SCREENS = {
  '/': 'Home',
  '/lineup-and-schedule': 'Lineup',
  '/faq': 'FAQ',
  'location-and-accommodation': 'Home',
} as const;
